title: Tractorbeam
url: "https://tractorbeam.ten7.com"
plugins:
    - jekyll-relative-links
    - jekyll-feed
    - jekyll-seo-tag
relative_links:
    enabled: true
    collections: true
include:
    - index.md
nav:
    - title: "How To"
      is_mobile_nav_item: false
      subfolderitems:
          items:
              - title: "Getting Started"
                description: ""
                url: "/setup.html"
              - title: "Use"
                description: ""
                url: "/setup.html#use"
              - title: "Configuration"
                description: ""
                url: "/setup.html#configuration"
              - title: "Backing up databases"
                description: ""
                url: "/setup.html#backing-up-databases"
              - title: "Backing up files"
                description: ""
                url: "/setup.html#backing-up-files"
              - title: "Rolling directory backups"
                description: ""
                url: "/setup.html#rolling-directory-backups"
              - title: "Deployment"
                description: ""
                url: "/setup.html#deployment"
              - title: "Debugging"
                description: ""
                url: "/setup.html#debugging"
    - title: "Support"
      description: "Find the support you need"
      url: "/support.html"
      is_mobile_nav_item: true
    - title: "Github"
      description: "Check out our Github"
      url: "https://github.com/ten7/tractorbeam"
      is_mobile_nav_item: true
      is_button: true

footer:
  has_built_with_love: true
  html: |
    {{site.title}} is built and supported by TEN7—we create and care for Drupal-powered websites. We talk about {{site.title}} extensively in episode 93 of <a href="https://ten7.com/podcast">The TEN7 Podcast</a> with <a href="https://twitter.com/socketwench">@socketwench</a> titled <a href="https://ten7.com/podcast/episode/tractorbeam-our-open-source-multi-tier-backup-solution">Tractorbeam: Our open source multi-tier backup solution</a>

google_tag_manager:
  head_html: |
    <script>
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-N6K9NBR');
    </script>
  page_html: |
    <noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N6K9NBR"
    height="0" width="0" style="display: none; visibility: hidden"></iframe>
    </noscript>

markdown: kramdown

collections:
    pages:
        output: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - assets/_src/
    - clean-theme.gemspec
    - ansible/
    - ansible-hosts
    - ansible.cfg
    - Gemfile
    - Gemfile.lock
    - imagemin.js
    - LICENSE
    - node_modules/
    - npm-debug.log
    - package.json
    - package-lock.json
    - README.md
    - tsconfig.json
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - webpack.config.js
    - yarn.lock
